### ISSUE TITLE
pluto segfault with ipsec whack --rereadcerts

### ISSUE THREAD

**Issue by wofferl** [libreswan/libreswan#1005]
When using  ipsec whack --rereadcerts or ipsec whack --rereadall pluto crashes with active connections. The problem is, that pluto iterates over all connection types not only the configured one.

```
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32": 192.168.11.1/32===10.0.12.63[CN=Internet Appliance]---10.0.12.1...%any===192.168.12.1/32; unrouted; eroute owner: #0
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":     oriented; my_ip=unset; their_ip=unset; mycert=/etc/ipsec.d/server.crt; my_updown=ipsec _updown;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   xauth us:none, xauth them:none,  my_username=[any]; their_username=[any]
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   our auth:rsasig, their auth:rsasig, our autheap:none, their autheap:none;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   modecfg info: us:none, them:none, modecfg policy:push, dns:unset, domains:unset, cat:unset;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   sec_label:unset;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   CAs: 'CN=Internet Appliance'...'CN=Internet Appliance'
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   ike_life: 21600s; ipsec_life: 32400s; ipsec_max_bytes: 2^63B; ipsec_max_packets: 2^63; replay_window: 128; rekey_margin: 540s; rekey_fuzz: 100%; keyin;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   retransmit-interval: 500ms; retransmit-timeout: 60s; iketcp:no; iketcp-port:4500;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   initial-contact:no; cisco-unity:no; fake-strongswan:no; send-vendorid:no; send-no-esp-tfc:no;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   policy: IKEv1+RSASIG+ENCRYPT+TUNNEL+PFS+DECAP_DSCP+DONT_REKEY+IKE_FRAG_ALLOW+ESN_NO+ESN_YES;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   conn_prio: 32,32; interface: ipsec0@ens19; metric: 0; mtu: unset; sa_prio:auto; sa_tfc:none;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   nflog-group: unset; mark: 0/00000000, 16777216/0xff000000; vti-iface:unset; vti-routing:no; vti-shared:no; nic-offload:auto;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   our idtype: ID_DER_ASN1_DN; our id=CN=Internet Appliance; their idtype: %none; their id=(none)
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   dpd: passive; delay:0s; timeout:0s
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   nat-traversal: encaps:auto; keepalive:20s; ikev1-method:rfc+drafts
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   newest ISAKMP SA: #0; newest IPsec SA: #0; conn serial: $2;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   IKE algorithms: AES_CBC_256-HMAC_SHA2_256-MODP2048, AES_CBC_256-HMAC_SHA2_256-MODP1536
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32":   ESP algorithms: AES_CBC_256-HMAC_SHA2_256_128
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]: 192.168.11.1/32===10.0.12.63[CN=Internet Appliance]---10.0.12.1...10.0.11.3[CN=Internet Appliance]===192.168.12.1/32; erouted; eroute owner: #2
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:     oriented; my_ip=unset; their_ip=unset; mycert=/etc/ipsec.d/server.crt; my_updown=ipsec _updown;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   xauth us:none, xauth them:none,  my_username=[any]; their_username=[any]
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   our auth:rsasig, their auth:rsasig, our autheap:none, their autheap:none;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   modecfg info: us:none, them:none, modecfg policy:push, dns:unset, domains:unset, cat:unset;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   sec_label:unset;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   CAs: 'CN=Internet Appliance'...'CN=Internet Appliance'
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   ike_life: 21600s; ipsec_life: 32400s; ipsec_max_bytes: 2^63B; ipsec_max_packets: 2^63; replay_window: 128; rekey_margin: 540s; rekey_fuzz: 100%; ke;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   retransmit-interval: 500ms; retransmit-timeout: 60s; iketcp:no; iketcp-port:4500;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   initial-contact:no; cisco-unity:no; fake-strongswan:no; send-vendorid:no; send-no-esp-tfc:no;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   policy: IKEv1+RSASIG+ENCRYPT+TUNNEL+PFS+DECAP_DSCP+DONT_REKEY+IKE_FRAG_ALLOW+ESN_NO+ESN_YES;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   conn_prio: 32,32; interface: ipsec0@ens19; metric: 0; mtu: unset; sa_prio:auto; sa_tfc:none;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   nflog-group: unset; mark: 0/00000000, 16777216/0xff000000; vti-iface:unset; vti-routing:no; vti-shared:no; nic-offload:auto;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   our idtype: ID_DER_ASN1_DN; our id=CN=Internet Appliance; their idtype: ID_DER_ASN1_DN; their id=CN=Internet Appliance
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   dpd: passive; delay:0s; timeout:0s
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   nat-traversal: encaps:auto; keepalive:20s; ikev1-method:rfc+drafts
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   newest ISAKMP SA: #1; newest IPsec SA: #2; conn serial: $4, instantiated from: $2;
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   IKE algorithms: AES_CBC_256-HMAC_SHA2_256-MODP2048, AES_CBC_256-HMAC_SHA2_256-MODP1536
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   IKEv1 algorithm newest: AES_CBC_256-HMAC_SHA2_256-MODP2048
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   ESP algorithms: AES_CBC_256-HMAC_SHA2_256_128
000 "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2]:   ESP algorithm newest: AES_CBC_256-HMAC_SHA2_256_128; pfsgroup=<Phase1>
000  
000 Total IPsec connections: loaded 3, active 1
000  
000 State Information: DDoS cookies not required, Accepting new IKE connections
000 IKE SAs: total(1), half-open(0), open(0), authenticated(1), anonymous(0)
000 IPsec SAs: total(1), authenticated(1), anonymous(0)
000  
000 #1: "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2] 10.0.11.3:1024 STATE_MAIN_R3 (IKE SA established); EXPIRE in 21597s; newest; lastdpd=-1s(seq in:0 out:0); idle;
000 #2: "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2] 10.0.11.3:1024 STATE_QUICK_R2 (IPsec SA established); EXPIRE in 32397s; newest; eroute owner; ISAKMP SA #1; idle;
000 #2: "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2] 10.0.11.3 esp.eb19e267@10.0.11.3 esp.20a04bd1@10.0.12.63 tun.0@10.0.11.3 tun.0@10.0.12.63 Traffic: ESPin=0B ESPout=0B ESPmax=2^63B
```

Pluto tries to reload the certificate for the initiated connection which has no host end config and crashes:

```
Feb  7 03:00:35.623268: | FOR_EACH_CONNECTION_.... in (reread_cert_connections() +84 programs/pluto/nss_cert_reread.c)
Feb  7 03:00:35.623289: |   found "server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32"[2] 10.0.11.3
Feb  7 03:00:35.623356: | rereading certificate(s) for connection 'server_0-test_sn-sn_192.168.11.1/32-192.168.12.1/32'
Feb  7 03:00:35.623385: | delref fd@NULL (reread_cert() +66 programs/pluto/nss_cert_reread.c)
```

Here is the backtrace with the invalid host_end_config pointer.

```
Pluto initialized
[New Thread 0x7ffff5e8e6c0 (LWP 48985)]
[New Thread 0x7ffff568d6c0 (LWP 48986)]
[New Thread 0x7ffff4e8c6c0 (LWP 48987)]
[Detaching after fork from child process 48988]
[Detaching after vfork from child process 48995]
[Detaching after vfork from child process 48997]
[Detaching after vfork from child process 48999]

Thread 1 "pluto" received signal SIGSEGV, Segmentation fault.
0x00005555556529b8 in reread_end_cert (logger=0x555555812538, host_end_config=0x170, host_end=0x55555586fc48) at /root/libreswan/programs/pluto/nss_cert_reread.c:15
15              if (host_end_config->cert.nss_cert == NULL) {
Missing separate debuginfos, use: dnf debuginfo-install audit-libs-3.0.9-1.fc37.x86_64 cyrus-sasl-lib-2.1.28-8.fc37.x86_64 glibc-2.36-7.fc37.x86_64 keyutils-libs-1.6.1-5.fc37.x86_64 krb5-libs-1.19.2-11.fc37.1.x86_64 ldns-1.8.1-7.fc37.x86_64 libbrotli-1.0.9-9.fc37.x86_64 libcap-2.48-5.fc37.x86_64 libcap-ng-0.8.3-3.fc37.x86_64 libcom_err-1.46.5-3.fc37.x86_64 libcurl-7.85.0-2.fc37.x86_64 libeconf-0.4.0-4.fc37.x86_64 libevent-2.1.12-7.fc37.x86_64 libffi-3.4.2-9.fc37.x86_64 libgcc-12.2.1-2.fc37.x86_64 libidn2-2.3.4-1.fc37.x86_64 libnghttp2-1.49.0-1.fc37.x86_64 libseccomp-2.5.3-3.fc37.x86_64 libselinux-3.4-5.fc37.x86_64 libssh-0.10.4-2.fc37.x86_64 libtasn1-4.18.0-3.fc37.x86_64 libunistring-1.0-2.fc37.x86_64 libxcrypt-4.4.30-3.fc37.x86_64 libzstd-1.5.2-3.fc37.x86_64 lz4-libs-1.9.3-5.fc37.x86_64 nspr-4.35.0-1.fc37.x86_64 nss-3.83.0-1.fc37.x86_64 nss-softokn-freebl-3.83.0-1.fc37.x86_64 nss-util-3.83.0-1.fc37.x86_64 openldap-2.6.3-1.fc37.x86_64 opensc-0.22.0-7.fc37.x86_64 openssl-libs-3.0.5-3.fc37.x86_64 p11-kit-0.24.1-3.fc37.x86_64 p11-kit-trust-0.24.1-3.fc37.x86_64 pam-libs-1.5.2-14.fc37.x86_64 pcre2-10.40-1.fc37.1.x86_64 protobuf-c-1.4.1-2.fc37.x86_64 python3-libs-3.11.0-1.fc37.x86_64 systemd-libs-251.10-588.fc37.x86_64 unbound-libs-1.17.1-1.fc37.x86_64 xz-libs-5.2.5-10.fc37.x86_64 zlib-1.2.12-5.fc37.x86_64
(gdb) bt
#0  0x00005555556529b8 in reread_end_cert (logger=0x555555812538, host_end_config=0x170, host_end=0x55555586fc48) at /root/libreswan/programs/pluto/nss_cert_reread.c:15
#1  reread_cert (logger=0x7fffffffd920, c=0x55555586fa28) at /root/libreswan/programs/pluto/nss_cert_reread.c:73
#2  reread_cert_connections (logger=logger@entry=0x7fffffffd920) at /root/libreswan/programs/pluto/nss_cert_reread.c:87
#3  0x0000555555642129 in whack_process (s=0x555555869c38, m=0x7fffffffbf60) at /root/libreswan/programs/pluto/rcv_whack.c:817
#4  whack_handle (whackfd=<optimized out>, whack_logger=whack_logger@entry=0x7fffffffd920) at /root/libreswan/programs/pluto/rcv_whack.c:1192
#5  0x00005555556432f9 in whack_handle_cb (fd=4, arg=<optimized out>, global_logger=0x7fffffffd980) at /root/libreswan/programs/pluto/rcv_whack.c:1095
#6  0x0000555555608912 in fd_read_listener_event_handler (fd=<optimized out>, events=<optimized out>, arg=<optimized out>) at /root/libreswan/programs/pluto/server.c:795
#7  0x00007ffff7935ca5 in event_process_active_single_queue () from /lib64/libevent_core-2.1.so.7
#8  0x00007ffff793780f in event_base_loop () from /lib64/libevent_core-2.1.so.7
#9  0x000055555560b13e in run_server (conffile=0x55555578fc38 "/etc/ipsec.conf", logger=0x7fffffffdbf0) at /root/libreswan/programs/pluto/server.c:1070
#10 0x000055555559cbdd in main (argc=<optimized out>, argv=<optimized out>) at /root/libreswan/programs/pluto/plutomain.c:1825

```
My workaround is to only call reread_cert for CK_TEMPLATE and CK_PERMANENT. 
I don't now if there is a better way.

```
diff --git a/programs/pluto/nss_cert_reread.c b/programs/pluto/nss_cert_reread.c
index c21f147c00..03ef130f7a 100644
--- a/programs/pluto/nss_cert_reread.c
+++ b/programs/pluto/nss_cert_reread.c
@@ -84,6 +84,7 @@ void reread_cert_connections(struct logger *logger)
        struct connection_filter cf = { .where = HERE, };
        while (next_connection_new2old(&cf)) {
                struct connection *c = cf.c;
-               reread_cert(c, logger);
+               if(c->kind == CK_PERMANENT || c->kind == CK_TEMPLATE)
+                       reread_cert(c, logger);
        }
 }
```

Btw --rereadall still uses rereadcrls instead of fetchcrls.
`003 ipsec whack: rereadcrls command obsoleted did you mean ipsec whack --fetchcrls`

**Comment by cagney** [comment]
> Btw --rereadall still uses rereadcrls instead of fetchcrls.

It was setting both the rereadcrls and fetchcrls bits so, while complaining, should still fetch them.

**Comment by cagney** [comment]
> My workaround is to only call reread_cert for CK_TEMPLATE and CK_PERMANENT.

It isn't far off.   Now that all the connections in a tree share a common config config, only the root connection needs to re-read certs.  Hence CK_PERMANENT and CK_TEMPLATE (mostly, it is sometimes instantiated from CK_GROUP).

I'll tweak mainline to check for a non-NULL .root_config.
