### ISSUE TITLE
pluto segfault when addresspool family differs from the host family

### ISSUE THREAD

**Issue by wofferl** [libreswan/libreswan#1062]
The actual git version (f93f13e40a09e22b7c0081a63f38e4608193a185) crashes when using different address families with address pools.

I added the two cases to the addconn-14-addresspool test to reproduce this issue easily.
[addconn-14-addresspool.patch](https://gist.github.com/wofferl/38202166b6bab9d1cea46b07d4ba858d)

The problem seems to be, that the address family from the address pool is not handled correctly.

```
"4to4in6": Child SA proposals (connection add):
"4to4in6":   1:ESP=AES_GCM_C_256-NONE-NONE-ENABLED+DISABLED
"4to4in6":   2:ESP=AES_GCM_C_128-NONE-NONE-ENABLED+DISABLED
"4to4in6":   3:ESP=AES_CBC_256-HMAC_SHA2_512_256+HMAC_SHA2_256_128-NONE-ENABLED+DISABLED
"4to4in6":   4:ESP=AES_CBC_128-HMAC_SHA2_512_256+HMAC_SHA2_256_128-NONE-ENABLED+DISABLED
| "4to4in6" c->sa_reqid=0 because wm->sa_reqid=0 and sec-label=n/a
| connection is permanent: by default
| fake leftauth=rsasig leftauthby=RSASIG+ECDSA+RSASIG_v1_5 from whack authby none
| ttoranges_num() input: 192.168.1.0/24
| ttoranges_num() nr tokens 1
| pool 192.168.1.0-192.168.1.255: reusing existing address pool@0x55ecd74da9e8; pool-refcount 2 size 256 leases 0 in-use 0 free 0 reusable 0
| addref struct addresspool@0x55ecd74da9e8(2->3) (addresspool_addref() +701 programs/pluto/addresspool.c)
| forced left modecfg client=yes right modecfg server=yes
| fake rightauth=rsasig rightauthby=RSASIG+ECDSA+RSASIG_v1_5 from whack authby none
| updating host ends from left.host.addr 2001:db8:1:2::45
|   updated left.host_port from 0 to 500
|   updated right.host_nexthop from :: to 2001:db8:1:2::45
| updating host ends from right.host.addr 2001:db8:1:2::23
|   updated right.host_port from 0 to 500
|   updated left.host_nexthop from :: to 2001:db8:1:2::23
| left child selectors unknown; probably derived from host?!?
| right child selectors from rightsubnet (selector); right.config.has_client=true
| ttoselectors_num() input: 192.168.2.0/24
| ttoselectors_num() nr tokens 1
| child.reqid=16404 because c->sa_reqid=0 (generate)
| select from address proto port
| set_end_selector_where() set left.child.selector 2001:db8:1:2::45/128 (set_connection_spds() +1421 programs/pluto/connections.c)
| select from child.selectors
| right.child.has_client: no -> yes (set_connection_spds() +1406 programs/pluto/connections.c)
| adding connection spds using proposed
|  left=1 right=1
|   left[IPv4]=0 right[IPv4]=1
|   left[IPv6]=1 right[IPv6]=0
| allocating 0 SPDs
```

Here is the core dump:
```
Core was generated by `/usr/local/libexec/ipsec/pluto --config /etc/ipsec.conf --leak-detective'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055ecd5576a35 in set_connection_priority (c=0x55ecd74e6d28) at /home/build/libreswan/programs/pluto/connections.c:2815
2815            c->priority = (((connection_priority_t)c->spd->local->client.maskbits << 17) |
[Current thread is 1 (Thread 0x7f75b0f334c0 (LWP 441287))]
Missing separate debuginfos, use: dnf debuginfo-install audit-libs-3.0.1-2.fc32.x86_64 glibc-2.31-6.fc32.x86_64 keyutils-libs-1.6.1-1.fc32.x86_64 krb5-libs-1.18.2-29.fc32.x86_64 libbrotli-1.0.9-3.fc32.x86_64 lib4
(gdb) bt
#0  0x000055ecd5576a35 in set_connection_priority (c=0x55ecd74e6d28) at /home/build/libreswan/programs/pluto/connections.c:2815
#1  add_connection_spds (c=c@entry=0x55ecd74e6d28, host_afi=host_afi@entry=0x55ecd56cdb30 <ip_families+400>) at /home/build/libreswan/programs/pluto/connections.c:1541
#2  0x000055ecd557bd37 in set_connection_spds (host_afi=<optimized out>, c=0x55ecd74e6d28) at /home/build/libreswan/programs/pluto/connections.c:1438
#3  extract_connection (c=<optimized out>, wm=0x55ecd5636cef) at /home/build/libreswan/programs/pluto/connections.c:2713
#4  add_connection (wm=wm@entry=0x7ffe6f5e28b0, logger=logger@entry=0x7ffe6f5e3e60) at /home/build/libreswan/programs/pluto/connections.c:2752
#5  0x000055ecd55cea00 in whack_process (s=0x55ecd74e68c8, m=0x7ffe6f5e28b0) at /home/build/libreswan/programs/pluto/rcv_whack.c:736
#6  whack_handle (whackfd=<optimized out>, whack_logger=whack_logger@entry=0x7ffe6f5e3e60) at /home/build/libreswan/programs/pluto/rcv_whack.c:1234
#7  0x000055ecd55d0979 in whack_handle_cb (fd=4, arg=<optimized out>, global_logger=0x7ffe6f5e3ec0) at /home/build/libreswan/programs/pluto/rcv_whack.c:1137
#8  0x000055ecd5596442 in fd_read_listener_event_handler (fd=<optimized out>, events=<optimized out>, arg=<optimized out>) at /home/build/libreswan/programs/pluto/server.c:794
#9  0x00007f75b20b852a in event_persist_closure (ev=<optimized out>, base=0x55ecd73f2718) at event.c:1580
#10 event_process_active_single_queue (base=base@entry=0x55ecd73f2718, activeq=0x55ecd74c4008, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0) at event.c:1639
#11 0x00007f75b20b8c27 in event_process_active (base=0x55ecd73f2718) at event.c:1738
#12 event_base_loop (base=0x55ecd73f2718, flags=flags@entry=0) at event.c:1961
#13 0x000055ecd5598bcf in run_server (conffile=0x55ecd73defa8 "/etc/ipsec.conf", logger=0x7ffe6f5e4100) at /home/build/libreswan/programs/pluto/server.c:1069
#14 0x000055ecd5529db7 in main (argc=<optimized out>, argv=<optimized out>) at /home/build/libreswan/programs/pluto/plutomain.c:1824
```

**Comment by cagney** [comment]
Nice catch.  I pushed the testcase change.

**Comment by cagney** [comment]
> but is there a 4to4in6 addresspool test showing establish?

that didn't go well
