### ISSUE TITLE
barf trying to write TS

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1103]
```
#0  0x0000555a254aa55c in emit_v2TS_selector (selector=..., ts_pbs=0x7ffe8b647590) at /source/programs/pluto/ikev2_ts.c:304
#1  emit_v2TS_payload (outpbs=outpbs@entry=0x7ffe8b647ad0, child=child@entry=0x7faf23551378, ts_desc=<optimized out>, selectors=0x7faf24185e00, sec_label=..., impaired_biased_len=0, name=0x555a255a5
952 "local TSi") at /source/programs/pluto/ikev2_ts.c:466
#2  0x0000555a254ac0ba in emit_v2TS_request_payloads (out=out@entry=0x7ffe8b647ad0, child=child@entry=0x7faf23551378) at /source/programs/pluto/ikev2_ts.c:485
#3  0x0000555a2553bbb2 in emit_v2_child_request_payloads (ike=ike@entry=0x7faf238e4378, larval_child=larval_child@entry=0x7faf23551378, child_proposals=<optimized out>, pbs=0x7ffe8b647ad0) at /source/programs/pluto/ikev2_child.c:224
#4  0x0000555a2549fe8b in initiate_v2_IKE_AUTH_request_signature_continue (ike=0x7faf238e4378, md=<optimized out>, auth_sig=<optimized out>) at /source/programs/pluto/ikev2_ike_auth.c:462
#5  0x0000555a25511d24 in handle_helper_answer (st=0x7faf238e4378, md=0x7faf23645608, arg=0x7faf235a1f98) at /source/programs/pluto/server_pool.c:450
#6  0x0000555a2550f79b in resume_handler (arg=0x7faf235bbfd8, logger=0x7ffe8b647ed0) at /source/programs/pluto/server.c:655
#7  0x0000555a2550e120 in timeout (fd=<optimized out>, event=<optimized out>, arg=<optimized out>) at /source/programs/pluto/server.c:553
#8  0x00007faf282b0c52 in event_process_active_single_queue (base=base@entry=0x7faf24289d68, activeq=0x7faf2428ffe8, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0) at /usr/src/debug/libevent-2.1.12-6.fc36.x86_64/event.c:1691
#9  0x00007faf282b28ef in event_process_active (base=0x7faf24289d68) at /usr/src/debug/libevent-2.1.12-6.fc36.x86_64/event.c:1783
#10 event_base_loop (base=0x7faf24289d68, flags=flags@entry=0) at /usr/src/debug/libevent-2.1.12-6.fc36.x86_64/event.c:2006
#11 0x0000555a255109be in run_server (conffile=0x7faf26e09fe8 "/etc/ipsec.conf", logger=0x7ffe8b648120) at /source/programs/pluto/server.c:1069
#12 0x0000555a25499d95 in main (argc=<optimized out>, argv=<optimized out>) at /source/programs/pluto/plutomain.c:1824
```
at line:
```
305.isath_type = afi->ikev2_ts_addr_range_type,
```
so presumably the address is unset

See `nss-cert-11-ca-expiring-responder-switch-ikev2-rw`

**Comment by cagney** [comment]
see also #937

**Comment by cagney** [comment]
the config:
```
conn old-west
	also=common
	leftcert=old-west
        left=192.1.2.45

conn common
	authby=rsasig
	# LEFT topology
	leftaddresspool=192.0.1.0/24
	# RIGHT topology
        right=192.1.2.23
	rightsubnet=192.0.2.0/24
	# authentication
        leftid=%fromcert
        leftrsasigkey=%cert
        rightid=%fromcert
        rightrsasigkey=%cert
	leftsendcert=always
	rightsendcert=always
```
resulted in a CK_PERMANENT connection with unknown left-selectors.

Per #937 it should have auto-added narrowing=yes for left

**Comment by cagney** [comment]
fe15318dc05dd3ccc4d9e6f24810f414f4353419
