### ISSUE TITLE
trying to restore an unrouted revival

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1204]
In `ikev2-xfrmi-12-two-default-routes` during shutdown:
```
Jul 23 16:52:11.795059: | "north-west": routing: dispatch UNROUTE to ROUTED_ONDEMAND PERMANENT $2 (delete_every_connection() +423 programs/pluto/connections.c)
Jul 23 16:52:11.795098: | bare_spd_owner() looking for SPD owner of 0.0.0.0/0->0.0.0.0/0 with routing >= UNROUTED_REVIVAL
Jul 23 16:52:11.795150: | FOR_EACH_SPD_ROUTE[remote_client_range=0.0.0.0/0]... in (delete_every_connection() +423 programs/pluto/connections.c)
Jul 23 16:52:11.795200: |   found "north-east" 0.0.0.0/0->0.0.0.0/0
Jul 23 16:52:11.795245: |    UNROUTED_REVIVAL 0.0.0.0/0->0.0.0.0/0 "north-east" policy saved; first match
Jul 23 16:52:11.795282: |   found "north-west" 0.0.0.0/0->0.0.0.0/0
Jul 23 16:52:11.795325: |    ROUTED_ONDEMAND 0.0.0.0/0->0.0.0.0/0 "north-west" skipped; ignoring self
Jul 23 16:52:11.795363: |   matches: 2
Jul 23 16:52:11.795400: FATAL: ASSERTION FAILED: switch (routing) case 1 (0x1) unexpected (routing_shunt_kind() +217 programs/pluto/routing.c)
```
and:
```
#7  0x0000561f5830daf3 in libreswan_bad_case (expression=expression@entry=0x561f5834f174 "routing", value=<optimized out>, where=where@entry=0x561f583c71a0 <here>) at /source/lib/libswan/libreswan_bad_case.c:25
#8  0x0000561f582881f5 in routing_shunt_kind (routing=<optimized out>) at /source/programs/pluto/routing.c:217
#9  0x0000561f5824fc72 in restore_spd_kernel_policy (spd=0x7ff54c9dcef8, logger=logger@entry=0x7ff54c9e6fc8, where=where@entry=0x561f583c6320 <here>, what=what@entry=0x561f5834f234 "unroute permanent", direction=DIRECTION_OUTBOUND) at /source/programs/pluto/kernel_policy.c:436
#10 0x0000561f582502f3 in delete_spd_kernel_policy (spd=spd@entry=0x7ff54c895ef8, direction=direction@entry=DIRECTION_OUTBOUND, existing_policy_expectation=existing_policy_expectation@entry=EXPECT_KERNEL_POLICY_OK, logger=logger@entry=0x7ff54c9e6fc8, where=where@entry=0x561f583c6320 <here>, story=story@entry=0x561f5834f234 "unroute permanent") at /source/programs/pluto/kernel_policy.c:516
#11 0x0000561f5825059b in delete_spd_kernel_policies (spds=0x7ff54c9e0ba0, inbound_policy_expectation=EXPECT_NO_INBOUND, logger=0x7ff54c9e6fc8, where=0x561f583c6320 <here>, story=0x561f5834f234 "unroute permanent") at /source/programs/pluto/kernel_policy.c:546
#12 0x0000561f5828941d in dispatch (event=event@entry=CONNECTION_UNROUTE, c=c@entry=0x7ffc7cf0b448, logger=0x7ff54c9e6fc8, where=where@entry=0x561f583c6320 <here>, ee=...) at /source/programs/pluto/routing.c:1118
#13 0x0000561f5828b5e8 in connection_unroute (c=<optimized out>, c@entry=0x7ff54c9e0ad8, where=where@entry=0x561f583c6320 <here>) at /source/programs/pluto/routing.c:879
#14 0x0000561f5827a655 in delete_every_connection () at /source/programs/pluto/connections.c:423
```

**Comment by cagney** [comment]
this change triggers it:
```
--- a/testing/pluto/ikev2-xfrmi-12-two-default-routes/ipsec.conf
+++ b/testing/pluto/ikev2-xfrmi-12-two-default-routes/ipsec.conf
@@ -16,7 +16,7 @@ conn north-east-default
        right=192.1.2.23
        rightnexthop=192.1.2.254
        rightsubnet=0/0
-       overlapip=yes
+       #overlapip=yes
 
 conn north-east
        also=north-east-default
@@ -32,7 +32,7 @@ conn north-west-default
        right=192.1.2.45
        rightnexthop=192.1.2.254
        rightsubnet=0/0
-       overlapip=yes
+       #overlapip=yes
 
 conn north-west
        also=north-west-default
```

**Comment by cagney** [comment]
no longer happens
