### ISSUE TITLE
in `ikev2-child-rekey-08-deadlock` pluto looses track of Child SA owning route

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1313]
```
"east/13x0": routing: start ESTABLISH_INBOUND Child#601(REKEY_CHILD_R0) to ROUTED_TUNNEL PERMANENT $13@0x7f5a612b6af8; newest routing#492 Child#492 (process_v2_child_request_payloads() +400 programs/pluto/ikev2_child.c)
"east/13x0": routing: stop ESTABLISH_INBOUND; ok=yes ROUTED_TUNNEL; newest routing#492->#601 Child#492 (process_v2_child_request_payloads() +400 programs/pluto/ikev2_child.c)
"east/13x0": routing: start ESTABLISH_OUTBOUND Child#601(REKEY_CHILD_R0) to ROUTED_TUNNEL PERMANENT $13@0x7f5a612b6af8; newest routing#601 Child#492 (process_v2_child_request_payloads() +400 programs/pluto/ikev2_child.c)
"east/13x0": routing: stop ESTABLISH_OUTBOUND; ok=yes ROUTED_TUNNEL; newest routing#601 Child#492->#601 (process_v2_child_request_payloads() +400 programs/pluto/ikev2_child.c)
"east/42x0": routing: start ESTABLISH_INBOUND Child#602(REKEY_CHILD_R0) to ROUTED_TUNNEL PERMANENT $42@0x7f5a5fddbaf8; newest routing#503 Child#503 (process_v2_child_request_payloads() +400 programs/pluto/ikev2_child.c)
...
"east/13x0": routing: start ESTABLISH_INBOUND Child#708(REKEY_CHILD_R0) to ROUTED_TUNNEL PERMANENT $13@0x7f5a612b6af8; newest routing#601 Child#601 (process_v2_child_request_payloads() +400 programs/pluto/ikev2_child.c)
"east/13x0": routing: stop ESTABLISH_INBOUND; ok=yes ROUTED_TUNNEL; newest routing#601->#708 Child#601 (process_v2_child_request_payloads() +400 programs/pluto/ikev2_child.c)
"east/13x0": routing: start ESTABLISH_OUTBOUND Child#708(REKEY_CHILD_R0) to ROUTED_TUNNEL PERMANENT $13@0x7f5a612b6af8; newest routing#708 Child#601 (process_v2_child_request_payloads() +400 programs/pluto/ikev2_child.c)
"east/13x0": routing: stop ESTABLISH_OUTBOUND; ok=yes ROUTED_TUNNEL; newest routing#708 Child#601->#708 (process_v2_child_request_payloads() +400 programs/pluto/ikev2_child.c)
...
EXPECTATION FAILED: "east/100x0": child->sa.st_connection->newest_routing_sa == child->sa.st_serialno (whack_connection_states() +483 programs/pluto/whack_connection.c)
FATAL: ASSERTION FAILED: "east/100x0" #1: unexpected Child SA "east/13x0" #601 (delete_state() +760 programs/pluto/state.c)

#6  0x000055e2b9628f39 in delete_state (st=0x7f5a623ad2f8) at /source/programs/pluto/state.c:759
#7  0x000055e2b95d950a in whack_connection_states (c=0x7f5a5d549af8, whack_state=whack_state@entry=0x55e2b961ebe0 <delete_states>, where=where@entry=0x55e2b9752a90 <here>) at /source/programs/pluto/whack_connection.c:509
#8  0x000055e2b961f0c7 in terminate_all_connection_states (c=<optimized out>, where=where@entry=0x55e2b9752a90 <here>) at /source/programs/pluto/terminate.c:203
#9  0x000055e2b95dc4cb in whack_delete_connection (cp=cp@entry=0x7fff41866310, logger=logger@entry=0x55e2b9782d00 <global_logger>) at /source/programs/pluto/whack_delete.c:136
#10 0x000055e2b95de06d in delete_every_connection () at /source/programs/pluto/whack_shutdown.c:123
#11 exit_epilogue () at /source/programs/pluto/whack_shutdown.c:154
#12 0x000055e2b95de1fd in server_stopped_callback (r=<optimized out>) at /source/programs/pluto/whack_shutdown.c:307
#13 0x000055e2b962fcfc in run_server (conffile=0x7f5a6501bfe8 "/etc/ipsec.conf", logger=0x7fff418664e0) at /source/programs/pluto/server.c:1070
#14 0x000055e2b95b0f4f in main (argc=<optimized out>, argv=<optimized out>) at /source/programs/pluto/plutomain.c:1832
```

**Comment by cagney** [comment]
fixed by d6d9e36fe91fa3529b8c9937b6089f4052a7fb49
