### ISSUE TITLE
newer python breaks testing

### ISSUE THREAD

**Issue by paulwouters** [libreswan/libreswan#1848]
### What happened?

ikev2-05-basic-psk  8.01: test domains: west east
ikev2-05-basic-psk  8.01: ****** ikev2-05-basic-psk (test 1 of 1) started ....
ikev2-05-basic-psk  8.01: moving contents of '../ikev2-05-basic-psk/OUTPUT' to 'BACKUP/2024-10-15-203442/ikev2-05-basic-psk'
Traceback (most recent call last):
  File "/home/paul/libreswan/testing/utils/fab/runner.py", line 299, in _process_test
    with logger.debug_time("testing %s", task.prefix,
         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
                           logfile=os.path.join(test.output_directory, "debug.log"),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                           loglevel=logutil.INFO) as test_runtime:
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/libreswan/testing/utils/fab/logutil.py", line 222, in __enter__
    self.logger_adapter.debug("starting debug log at %s",
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              datetime.now())
                              ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1900, in debug
    self.log(DEBUG, msg, *args, **kwargs)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1944, in log
    self.logger.log(level, msg, *args, **kwargs)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1589, in log
    self._log(level, msg, args, **kwargs)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1664, in _log
    self.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1680, in handle
    self.callHandlers(record)
    ~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1736, in callHandlers
    hdlr.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1025, in handle
    with self.lock:
         ^^^^^^^^^
AttributeError: 'DebugHandler' object has no attribute 'lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paul/libreswan/testing/utils/fab/runner.py", line 498, in _process_test
    logger.info("single test run; leaving domains running");
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1906, in info
    self.log(INFO, msg, *args, **kwargs)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1944, in log
    self.logger.log(level, msg, *args, **kwargs)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1589, in log
    self._log(level, msg, args, **kwargs)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1664, in _log
    self.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1680, in handle
    self.callHandlers(record)
    ~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1736, in callHandlers
    hdlr.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1025, in handle
    with self.lock:
         ^^^^^^^^^
AttributeError: 'DebugHandler' object has no attribute 'lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paul/libreswan/testing/pluto/ikev2-05-basic-psk/../../utils/kvmrunner.py", line 109, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/paul/libreswan/testing/pluto/ikev2-05-basic-psk/../../utils/kvmrunner.py", line 94, in main
    runner.run_tests(logger, args, tests, result_stats)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/libreswan/testing/utils/fab/runner.py", line 634, in run_tests
    _process_test_queue(domain_prefix, test_queue, len(tests), args, done, result_stats)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/libreswan/testing/utils/fab/runner.py", line 568, in _process_test_queue
    _process_test(domain_prefix, domains, args,
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  result_stats, task, task_logger)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/libreswan/testing/utils/fab/runner.py", line 229, in _process_test
    with logger.time("processing test %s", task.prefix):
         ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/libreswan/testing/utils/fab/logutil.py", line 203, in __exit__
    self.logger_adapter.log(self.loglevel, "stop %s after %s",
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            self.action, self.timer)
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1944, in log
    self.logger.log(level, msg, *args, **kwargs)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1589, in log
    self._log(level, msg, args, **kwargs)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1664, in _log
    self.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1680, in handle
    self.callHandlers(record)
    ~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1736, in callHandlers
    hdlr.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1025, in handle
    with self.lock:
         ^^^^^^^^^
AttributeError: 'DebugHandler' object has no attribute 'lock'
paul@thinkpad:~/libreswan/testing/pluto/ikev2-05-basic-psk (main)$ 



### Your configuration

_No response_

### Relevant log output

_No response_

**Comment by cagney** [comment]
this looks like an upstream regression, can you downgrade to 3.12

**Comment by cagney** [comment]
https://github.com/python/cpython/issues/125606

**Comment by cagney** [comment]
It turns out it was somewhat self inflicted, it was a workaround for https://bugs.python.org/issue36533#msg341768
see f783d792d0c5e03d96ad6233651e3363e52f36d1
