### ISSUE TITLE
core dump in sec_label code due to IPTFS

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1849]
### What happened?

`child` is `NULL`.  To quote:
```
 * Install (add, replace) a kernel policy for the SPD.  The kernel
 * policy is "bare" since there isn't yet a state.
```
digging deeper, kernel_policy_from_spd() shouldn't have an iptfs parameter - it's constructing the kernel policy based on the SPD, not the state.

### Relevant log output

```shell
| kernel: NIC esp-hw-offload disabled for connection 'labeled'

CRASHING THREAD:

#0  0x00005564daea6954 in add_sec_label_kernel_policy (spd=0x7f70fea59ef8, direction=direction@entry=DIRECTION_OUTBOUND, logger=logger@entry=0x7f70ff2d1fc8, where=where@entry=0x5564db020d90 <here>, what=what@entry=0x5564dafc8f58 "ondemand security label") at /source/programs/pluto/kernel_policy.c:288
#1  0x00005564daedd7a8 in unrouted_to_routed_ondemand_sec_label (c=c@entry=0x7f70ff2a5a78, logger=logger@entry=0x7f70ff2d1fc8, where=0x5564db020d90 <here>) at /source/programs/pluto/routing.c:615
#2  0x00005564daede6be in dispatch_1 (event=event@entry=CONNECTION_ROUTE, c=0x7f70ff2a5a78, logger=logger@entry=0x7f70ff2d1fc8, e=e@entry=0x7ffc9588b120) at /source/programs/pluto/routing.c:2350
#3  0x00005564daedf6e1 in dispatch (event=event@entry=CONNECTION_ROUTE, c=<optimized out>, c@entry=0x7f70ff2a5a78, logger=0x7f70ff2d1fc8, e=e@entry=0x7ffc9588b120) at /source/programs/pluto/routing.c:2491
#4  0x00005564daee0331 in connection_route (c=c@entry=0x7f70ff2a5a78, where=where@entry=0x5564db020d90 <here>) at /source/programs/pluto/routing.c:1587
#5  0x00005564dae9d1b7 in maybe_route_connection (c=0x7f70ff2a5a78) at /source/programs/pluto/whack_route.c:41
#6  whack_route_connection (m=<optimized out>, s=0x7f70ff2adba8, c=0x7f70ff2a5a78) at /source/programs/pluto/whack_route.c:76
#7  0x00005564dae96de7 in visit_connections_bottom_up (c=<optimized out>, m=0x7ffc9588b930, s=0x7f70ff2adba8, visit_connection=0x5564dae9d0e0 <whack_route_connection>) at /source/programs/pluto/whack_connection.c:293
#8  0x00005564dae96fa9 in whack_connections_by_name (each=0x7ffc9588b5a8, m=0x7ffc9588b930, s=0x7f70ff2adba8, visit_connections=0x5564dae96d10 <visit_connections_bottom_up>, visit_connection=0x5564dae9d0e0 <whack_route_connection>) at /source/programs/pluto/whack_connection.c:86
#9  whack_connections (m=m@entry=0x7ffc9588b930, s=s@entry=0x7f70ff2adba8, visit_connections=visit_connections@entry=0x5564dae96d10 <visit_connections_bottom_up>, visit_connection=visit_connection@entry=0x5564dae9d0e0 <whack_route_connection>, alias_order=alias_order@entry=NEW2OLD, each=each@entry=0x7ffc9588b5a8) at /source/programs/pluto/whack_connection.c:313
#10 0x00005564dae97561 in whack_connections_bottom_up (m=m@entry=0x7ffc9588b930, s=s@entry=0x7f70ff2adba8, visit_connection=visit_connection@entry=0x5564dae9d0e0 <whack_route_connection>, each=...) at /source/programs/pluto/whack_connection.c:404
#11 0x00005564dae9d2d4 in whack_route (m=m@entry=0x7ffc9588b930, s=s@entry=0x7f70ff2adba8) at /source/programs/pluto/whack_route.c:96
#12 0x00005564dae94d37 in whack_process (m=0x7ffc9588b930, s=0x7f70ff2adba8) at /source/programs/pluto/rcv_whack.c:580
#13 whack_handle (whackfd=<optimized out>, whack_logger=whack_logger@entry=0x7ffc9588cfc0) at /source/programs/pluto/rcv_whack.c:839
#14 0x00005564dae96177 in whack_handle_cb (fd=4, arg=<optimized out>, global_logger=0x7ffc9588d020) at /source/programs/pluto/rcv_whack.c:777
#15 0x00005564daef09b0 in fd_read_listener_event_handler (fd=<optimized out>, events=<optimized out>, arg=<optimized out>) at /source/programs/pluto/server.c:802
#16 0x00007f7101ac600a in event_process_active_single_queue () from /lib64/libevent_core-2.1.so.7
#17 0x00007f7101ac7eaf in event_base_loop () from /lib64/libevent_core-2.1.so.7
#18 0x00005564daef32fe in run_server (conffile=0x7f710056efe8 "/etc/ipsec.conf", logger=0x5564db0538c0 <global_logger>) at /source/programs/pluto/server.c:1077
#19 0x00005564dae6b208 in main (argc=<optimized out>, argv=<optimized out>) at /source/programs/pluto/plutomain.c:1908

SOURCE CODE:

283.esp = (c->config->child_sa.encap_proto == ENCAP_PROTO_ESP),
284.ah = (c->config->child_sa.encap_proto == ENCAP_PROTO_AH),
285};
286struct child_sa *child = child_sa_by_serialno(c->established_child_sa);
287
288struct kernel_policy kernel_policy =
289kernel_policy_from_spd(policy, spd, kernel_mode,
290       child->sa.st_seen_and_use_iptfs, direction,
291       &nic_offload,
292       logger, where);

LOCAL VARIABLES:

c = <optimized out>
__func__ = <optimized out>
kernel_mode = KERNEL_MODE_TUNNEL
nic_offload = {dev = 0x0, type = KERNEL_OFFLOAD_NONE}
policy = {ipcomp = false, esp = true, ah = false}
child = 0x0
kernel_policy = {local = {client = {is_set = 80, version = 32764, bytes = {byte = "\371\352\220\001q\177\000\000@\250\210\225\374\177\000"}, maskbits = 26274748, ipproto = 32625, hport = 2}, route = {is_set = false, version = 2508761264, bytes = {byte = "\374\177\000\000r\231\374\332dU\000\000\260\251\210\225"}, maskbits = 32764, ipproto = 2508761200, hport = 32764}, host = {is_set = 188, version = 32625, bytes = {byte = "\002\000\000\000\000\000\000\000 \316W\000q\177\000"}}}, remote = {client = {is_set = 160, version = 32764, bytes = {byte = "\242\241\221\001q\177\000\000\260\250\210\225\374\177\000"}, maskbits = 2508761264, ipproto = 153, hport = 26269728}, route = {is_set = 113, version = 5754400, bytes = {byte = "q\177", '\000' <repeats 13 times>}, maskbits = 0, ipproto = 2508761312, hport = 32764}, host = {is_set = 224, version = 32764, bytes = {byte = "`\251\210\225\374\177\000\000\231\000\000\000\000\000\000"}}}, src = {client = {is_set = 4, version = 859712818, bytes = {byte = " \316W\000q\177\000\376\310\037-\377p\177\000"}, maskbits = 2508760288, ipproto = 32764, hport = 127}, route = {is_set = false, version = 1023, bytes = {byte = "\000\000\000\000\323\030\374\332dU\000\000\000\0000"}, maskbits = 0, ipproto = 0, hport = 0}, host = {is_set = false, version = 1646279493, bytes = {byte = "y=UNKNOW\000\024\310\321\265\266\375\256"}}}, dst = {client = {is_set = 120, version = 32624, bytes = {byte = "\310\037-\377p\177\000\000\220\r\002\333dU\000"}, maskbits = 3673568713, ipproto = 21860, hport = 48}, route = {is_set = 48, version = 2508761680, bytes = {byte = "\374\177\000\000p\251\210\225\374\177\000\000\000\024\310\321"}, maskbits = 2935862965, ipproto = 208, hport = 0}, host = {is_set = 178, version = 21860, bytes = {byte = "@\030\376\332dU\000\000\001\000\000\000\000\000\000"}}}, priority = {value = 0}, kind = SHUNT_KIND_NONE, shunt = 4280983528, where = 0x7ffc9588aad0, sec_label = {ptr = 0x0, len = 149}, sa_marks = 0x5564dafc18d3, ipsec_interface = 0x7ffc9588a9d0, id = (unknown: 0xd1c81400), mode = (KERNEL_MODE_TRANSPORT | unknown: 0xaefdb6b4), iptfs = 89, nr_rules = 21860, rule = {{proto = 2508761808, reqid = 32764}, {proto = 4280965752, reqid = 32624}, {proto = 3674344848, reqid = 21860}}, nic_offload = {dev = 0x7ffc9588aa90 "\273\222\374\332dU", type = (KERNEL_OFFLOAD_CRYPTO | unknown: 0xdaece128)}}
```

**Comment by paulwouters** [comment]
fixed. note this was only broken after 5.1 and before 5.2
