### ISSUE TITLE
./kvm recheck failure

### ISSUE THREAD

**Issue by paulwouters** [libreswan/libreswan#1851]
### What happened?

check-10-network-freebsd  14.02: stop processing test check-10-network-freebsd (test 5 of 1283) after 7.9 seconds
Traceback (most recent call last):
  File "/home/build/libreswan/testing/utils/kvmrunner.py", line 109, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/build/libreswan/testing/utils/kvmrunner.py", line 94, in main
    runner.run_tests(logger, args, tests, result_stats)
  File "/home/build/libreswan/testing/utils/fab/runner.py", line 634, in run_tests
    _process_test_queue(domain_prefix, test_queue, len(tests), args, done, result_stats)
  File "/home/build/libreswan/testing/utils/fab/runner.py", line 568, in _process_test_queue
    _process_test(domain_prefix, domains, args,
  File "/home/build/libreswan/testing/utils/fab/runner.py", line 306, in _process_test
    if not test_domain.start():
           ^^^^^^^^^^^^^^^^^^^
  File "/home/build/libreswan/testing/utils/fab/runner.py", line 108, in start
    console = remote.boot_and_login(self.domain)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/build/libreswan/testing/utils/fab/remote.py", line 174, in boot_and_login
    if not _login(console, logger, login=LOGIN, password=PASSWORD,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/build/libreswan/testing/utils/fab/remote.py", line 99, in _login
    console.run("export TERM=dumb ; unset LS_COLORS ; stty sane -echo -onlcr")
  File "/home/build/libreswan/testing/utils/fab/console.py", line 156, in run
    self.expect(self.prompt, timeout=timeout)
  File "/usr/lib/python3.12/site-packages/pexpect/spawnbase.py", line 354, in expect
    return self.expect_list(compiled_pattern_list,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pexpect/spawnbase.py", line 383, in expect_list
    return exp.expect_loop(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pexpect/expect.py", line 179, in expect_loop
    return self.eof(e)
           ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pexpect/expect.py", line 122, in eof
    raise exc
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<fab.console.Console object at 0x7f17380dee10>
command: /usr/bin/sudo
args: ['/usr/bin/sudo', 'virsh', '--connect', 'qemu:///system', 'start', 'east', '--console']
buffer (last 100 chars): b''
before (last 100 chars): b'error: stream had I/O failure\r\n\r\nexport TERM=dumb ; unset LS_COLORS ; stty sane -echo -onlcr\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 1
flag_eof: True
pid: 178971
child_fd: 6
closed: False
timeout: 10
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: <fab.console._Debug object at 0x7f17380dedb0>
logfile_send: <fab.console._Debug object at 0x7f17380defc0>
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'(|\\x1b\\[\\?2004h)([-a-z0-9]+|\\[(?P<username>[-.a-z0-9]+)@(?P<hostname>[-a-z0-9]+) (?P<basename>[-+=:,\\.a-z0-9A-Z_~]+)(| (?P<status>[0-9]+))\\])(?P<dollar>[#\\$]) ')
make: *** [Makefile:570: kvm-recheck] Error 1
make: Leaving directory '/home/build/libreswan/testing/kvm'

**Comment by cagney** [comment]
Probably the tests being run twice from the same directory
