### ISSUE TITLE
timeout running CD in domain

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1856]
```
pfkeyv2-tunnel-4in4-esp-ikev2 tb4netbsdw 2:11:47.03/1.02: domain started
pfkeyv2-tunnel-4in4-esp-ikev2 tb4netbsdw 2:12:07.01/20.09: boot successful (boot attempt 1 and 21.0 seconds)
pfkeyv2-tunnel-4in4-esp-ikev2 tb4netbsdw 2:12:07.02/21.00: got 'Last login' after 21.0 seconds; ignoring
pfkeyv2-tunnel-4in4-esp-ikev2 tb4netbsdw 2:12:07.02/21.00: we're in (after 21.1 seconds)!
```
this should be followed by `cd`, instead:
```
pfkeyv2-tunnel-4in4-esp-ikev2 tb4 2:12:17.03/31.02: stop booting tb4netbsdw domain after 31.2 seconds
pfkeyv2-tunnel-4in4-esp-ikev2 tb4 2:12:17.03: stopping domains: tb4netbsdw tb4east
pfkeyv2-tunnel-4in4-esp-ikev2 tb4netbsdw 2:12:17.03: spawning: sudo virsh --connect qemu:///system console --force tb4netbsdw
pfkeyv2-tunnel-4in4-esp-ikev2 tb4netbsdw 2:12:17.05: waiting 20 seconds for domain to be destroyed
pfkeyv2-tunnel-4in4-esp-ikev2 tb4netbsdw 2:12:17.08: domain destroyed after 0.3 seconds

pfkeyv2-tunnel-4in4-esp-ikev2 tb4 2:12:18.03:   total/failed: 186
pfkeyv2-tunnel-4in4-esp-ikev2 tb4 2:12:18.03:   total/ignored: 8
pfkeyv2-tunnel-4in4-esp-ikev2 tb4 2:12:18.03:   total/passed: 1042
pfkeyv2-tunnel-4in4-esp-ikev2 tb4 2:12:18.03:   total/unresolved: 1
pfkeyv2-tunnel-4in4-esp-ikev2 tb4 2:12:18.03: stop processing test pfkeyv2-tunnel-4in4-esp-ikev2 (test 1237 of 1283) after 32.2 seconds
Exception in thread tb4:
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.12/threading.py", line 1012, in run
kvmrunner 2:12:19.00: waiting for threads to finish
    self._target(*self._args, **self._kwargs)
  File "/home/libreswan/benchdir/testing/utils/fab/runner.py", line 549, in _process_test_queue
    _process_test(domain_prefix, domains, args,
  File "/home/libreswan/benchdir/testing/utils/fab/runner.py", line 311, in _process_test
    if not test_domain.start():
           ^^^^^^^^^^^^^^^^^^^
  File "/home/libreswan/benchdir/testing/utils/fab/runner.py", line 111, in start
    console.chdir(test_directory)
  File "/home/libreswan/benchdir/testing/utils/fab/console.py", line 164, in chdir
    if self.run("cd " + directory):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/libreswan/benchdir/testing/utils/fab/console.py", line 156, in run
    self.expect(self.prompt, timeout=timeout)
  File "/usr/lib/python3.12/site-packages/pexpect/spawnbase.py", line 354, in expect
    return self.expect_list(compiled_pattern_list,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pexpect/spawnbase.py", line 383, in expect_list
    return exp.expect_loop(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<fab.console.Console object at 0x7fbea8ced460>
command: /usr/bin/sudo
args: ['/usr/bin/sudo', 'virsh', '--connect', 'qemu:///system', 'start', 'tb4netbsdw', '--console']
buffer (last 100 chars): b''
before (last 100 chars): ''
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 1965752
child_fd: 12
closed: False
timeout: 10
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: <fab.console._Debug object at 0x7fbea8caf1d0>
logfile_send: <fab.console._Debug object at 0x7fbea8d0a660>
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'(|\\x1b\\[\\?2004h)([-a-z0-9]+|\\[(?P<username>[-.a-z0-9]+)@(?P<hostname>[-a-z0-9]+) (?P<basename>[-+=:,\\.a-z0-9A-Z_~]+)(| (?P<status>[0-9]+))\\])(?P<dollar>[#\\$]) ')
```

**Comment by cagney** [comment]
I suspect the automount hung.  Unfortunately because runner bailed, the debug.log for the test was lost

**Comment by cagney** [comment]
this has magically gone away
