### ISSUE TITLE
verify (/usr/libexec/ipsec/verify) error 

### ISSUE THREAD

**Issue by AnandBibhuti** [libreswan/libreswan#280]
# /usr/libexec/ipsec/verify
Verifying installed system and configuration files

Version check and ipsec on-path                   [OK]
Libreswan 3.29 (netkey) on 5.2.14-1942.el8uek.x86_64
Checking for IPsec support in kernel               [OK]
 NETKEY: Testing XFRM related proc values
         ICMP default/send_redirects               [NOT DISABLED]

  Disable /proc/sys/net/ipv4/conf/*/send_redirects or NETKEY will act on or
cause sending of bogus ICMP redirects!

         ICMP default/accept_redirects             [NOT DISABLED]

  Disable /proc/sys/net/ipv4/conf/*/accept_redirects or NETKEY will act on or
cause sending of bogus ICMP redirects!

         XFRM larval drop                         [OK]
Pluto ipsec.conf syntax                           [OK]
Checking rp_filter                                 [ENABLED]
 /proc/sys/net/ipv4/conf/all/rp_filter             [ENABLED]
  rp_filter is not fully aware of IPsec and should be disabled
Checking that pluto is running                     [FAILED]
Checking 'ip' command                             [OK]
Checking 'iptables' command                       [OK]
Checking 'prelink' command does not interfere with FIPS [OK]
Checking for obsolete ipsec.conf options           [OBSOLETE KEYWORD]
Traceback (most recent call last):
  File "/usr/libexec/ipsec/verify", line 394, in <module>
    main()
  File "/usr/libexec/ipsec/verify", line 385, in main
    configsetupcheck()
  File "/usr/libexec/ipsec/verify", line 366, in configsetupcheck
    err = err.replace("Warning"," Warning")
TypeError: a bytes-like object is required, not 'str'

This is when default python version is python3.

**Comment by letoams** [comment]
This issue has been fixed in git master with commit 6d1a1a7430c0f459730ce723d7d6c6faf3ad1f04
