### ISSUE TITLE
SEGV in pluto under Clear linux

### ISSUE THREAD

**Issue by Ralim** [libreswan/libreswan#291]
Hi,

Not sure if this is caused by the way `pluto` is compiled for Clear Linux, or if this is actually a bug in `pluto`.  Hoping someone can point me in either direction :smile: .

Happy to have a crack at debugging this further, but not overly sure where to go from there tbh.

Using the networkmanager-l2tp GUI to setup the VPN connections at the moment.

`/etc/ipsec.conf` is an empty file, should this have had some default config loaded in by the package?

Running pluto with the command line `pluto --leak-detective --config /etc/ipsec.conf --nofork` causes a SEGV to be thrown.

GDB frame and backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
pfree (ptr=0x0) at /usr/src/debug/libreswan-3.29/lib/libswan/alloc.c:133
133	in /usr/src/debug/libreswan-3.29/lib/libswan/alloc.c
(gdb) info frame
Stack level 0, frame at 0x7fffffffde80:
 rip = 0x5555555b4417 in pfree (/usr/src/debug/libreswan-3.29/lib/libswan/alloc.c:133); saved rip = 0x55555564882a
 called by frame at 0x7fffffffdee0
 source language c.
 Arglist at 0x7fffffffde48, args: ptr=0x0
 Locals at 0x7fffffffde48, Previous frame's sp is 0x7fffffffde80
 Saved registers:
  rbx at 0x7fffffffde60, rbp at 0x7fffffffde70, r12 at 0x7fffffffde68, rip at 0x7fffffffde78
(gdb) bt
#0  pfree (ptr=0x0) at /usr/src/debug/libreswan-3.29/lib/libswan/alloc.c:133
#1  0x000055555564882a in pfree (ptr=0x0) at /usr/src/debug/libreswan-3.29/lib/libswan/alloc.c:129
#2  concat_chunk_symkey (rhs=<optimized out>, lhs=..., name=<optimized out>) at /usr/src/debug/libreswan-3.29/programs/pluto/crypt_symkey.c:496
#3  append_chunk_symkey (rhs=<optimized out>, lhs=<optimized out>, name=<optimized out>) at /usr/src/debug/libreswan-3.29/programs/pluto/crypt_symkey.c:580
#4  nss_xcbc_digest_symkey (prf=0x5555557da3f8, symkey_name=<optimized out>, symkey=<optimized out>) at /usr/src/debug/libreswan-3.29/programs/pluto/ike_alg_prf_nss_xcbc_ops.c:260
#5  0x000055555559a8a1 in crypt_prf_update_symkey (update=0x0, name=0x555555684727 "symkey message", prf=0x5555557d3c18) at /usr/src/debug/libreswan-3.29/programs/pluto/crypt_prf.c:146
#6  test_prf_vector (test=0x5555556d7bc0 <aes_xcbc_prf_tests+8>, prf=<optimized out>) at /usr/src/debug/libreswan-3.29/programs/pluto/prf_test_vectors.c:156
#7  test_prf_vectors (tests=0x5555556d7bb8 <aes_xcbc_prf_tests>) at /usr/src/debug/libreswan-3.29/programs/pluto/prf_test_vectors.c:183
#8  test_ike_alg () at /usr/src/debug/libreswan-3.29/lib/libswan/ike_alg_test.c:39
#9  0x000055555557427f in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/libreswan-3.29/programs/pluto/plutomain.c:1757

```

It's built from libreswan 3.29 through the clear linux tooling (however that works) :) 

Thanks,
Ralim

**Comment by letoams** [comment]
I cannot reproduce this on my machine:
[root@thinkpad tmp]# cat /tmp/ipsec.conf 
[root@thinkpad tmp]# ls -l /tmp/ipsec.conf 
-rw-r--r-- 1 root root 0 Jan 28 18:17 /tmp/ipsec.conf
[root@thinkpad tmp]# /usr/libexec/ipsec/pluto --leak-detective --config /tmp/ipsec.conf --nofork
Pluto initialized

no crash.

**Comment by letoams** [comment]
If this still happens to you with 3.30, please re-open the bug
