### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#616]
https://testing.libreswan.org/v4.6-22-gfb74946cbc-main/kvm-test.log

Exception in thread w4.:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/build/libreswan-web/script-repo/testing/utils/fab/runner.py", line 502, in _process_test_queue
    _process_test(domain_prefix, args, result_stats, task, task_logger)
  File "/home/build/libreswan-web/script-repo/testing/utils/fab/runner.py", line 350, in _process_test
    test_domain.read_file_run(script.path)
  File "/home/build/libreswan-web/script-repo/testing/utils/fab/runner.py", line 139, in read_file_run
    status = self.console.run(line, timeout=TEST_TIMEOUT)
  File "/home/build/libreswan-web/script-repo/testing/utils/fab/shell.py", line 224, in run
    status = check_prompt(self.logger, self.child.match,
  File "/home/build/libreswan-web/script-repo/testing/utils/fab/shell.py", line 113, in check_prompt
    check_prompt_group(logger, match, basename, BASENAME_GROUP)
  File "/home/build/libreswan-web/script-repo/testing/utils/fab/shell.py", line 98, in check_prompt_group
    found = match.group(field).decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by cagney** [comment]
call deleted
