### ISSUE TITLE
kvmrunner crashed reading output from wait-for.sh

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#629]
https://testing.libreswan.org/v4.6-144-g303fab99cc-main/xauth-pluto-25-lsw299/OUTPUT/
```
INFO xauth-pluto-25-lsw299 w1.north 1:52:58.01/52.01: stop running script 04-north-up.sh after 0.6 seconds
INFO xauth-pluto-25-lsw299 w1.east 1:52:58.01/52.01: start running script 05-east-established.sh at 2022-02-03 01:19:19.859905
INFO xauth-pluto-25-lsw299 w1.east 1:52:58.01/52.01: [05-east-established.sh]# ../../guestbin/wait-for.sh --match '^[^|].* #2: IPsec SA established' -- cat /tmp/pluto.log
DEBUG xauth-pluto-25-lsw299 w1.east 1:52:58.01/52.01: run '../../guestbin/wait-for.sh --match '^[^|].* #2: IPsec SA established' -- cat /tmp/pluto.log' expecting prompt
DEBUG xauth-pluto-25-lsw299 w1.east 1:52:58.02/52.02: send <<b"../../guestbin/wait-for.sh --match '^[^|].* #2: IPsec SA established' -- cat /tmp/pluto.log\n">>>
DEBUG xauth-pluto-25-lsw299 w1.east 1:52:58.02/52.02: read <<b'[   46.869211] alg: No test for echainiv(authenc(hmac(sha1),cbc(aes))) (echainiv(authenc(hmac(sha1-generic),cbc(aes-generic))))\r\n'>>>
DEBUG xauth-pluto-25-lsw299 w1.east 1:53:27.06/1:21.06: read <<b'timeout waiting 30 seconds for cat /tmp/pluto.log to match ^[^|]'>>>
DEBUG xauth-pluto-25-lsw299 w1.east 1:53:27.06/1:21.07: read <<b'.* #2: IPsec SA established\n'>>>
DEBUG xauth-pluto-25-lsw299 w1.east 1:53:27.06/1:21.07: read <<b'outp'>>>
...
DEBUG xauth-pluto-25-lsw299 w1.east 1:53:27.07/1:21.07: read <<b'put: |   35 aa d5 9c  3b 93 '>>>
DEBUG xauth-pluto-25-lsw299 w1.east 1:53:27.07/1:21.07: read <<b'7e e3  86 c2 a9 93  58 0'>>>
DEBUG xauth-pluto-25-lsw299 w1.east 1:53:27.07/1:21.07: read <<b'7 2c 31   5...;.~.....X.,1\noutput: |   b0 05 f7 9d  cf 49 1d 88  99 aa 98 93  0f f5 eb 6e   .....I.........n\noutput: |   f5 56 3c 2c  21 73 9e 20  c7 22 81 c2  '>>>
DEBUG xauth-pluto-25-lsw299 w1.east 1:53:27.07/1:21.07: read <<b'b3 d7 ee 33   .V<,!s. .".....3\noutput: |   04 7a 77 f2  8c 6e 35 23  20 5c 70 57  cd 0b d8 a3   .zw..n5# \\pW....\noutput: |   71 75 11 e6  92 da 98 fb  f0 b8 1f 5b                qu.........[\noutput: | **parse ISAKMP Message:\noutput: | '>>>
DEBUG xauth-pluto-25-lsw299 w1.east 1:53:27.07/1:21.07: match <re.Match object; span=(3344, 3348), match=b'n5# '> contains {'username': None, 'hostname': None, 'basename': None, 'status': None, 'dollar': b'#'}
INFO xauth-pluto-25-lsw299 w1.east 1:53:27.07/1:21.07: stop running script 05-east-established.sh after 29.6 seconds
ERROR xauth-pluto-25-lsw299 w1. 1:53:27.07/1:21.07: *** EXCEPTION 'NoneType' object has no attribute 'decode' while running script east:05-east-established.sh ***
Traceback (most recent call last):
  File "/home/build/libreswan-web/script-repo/testing/utils/fab/runner.py", line 350, in _process_test
    test_domain.read_file_run(script.path)
  File "/home/build/libreswan-web/script-repo/testing/utils/fab/runner.py", line 139, in read_file_run
    status = self.console.run(line, timeout=TEST_TIMEOUT)
  File "/home/build/libreswan-web/script-repo/testing/utils/fab/shell.py", line 224, in run
    status = check_prompt(self.logger, self.child.match,
  File "/home/build/libreswan-web/script-repo/testing/utils/fab/shell.py", line 113, in check_prompt
    check_prompt_group(logger, match, basename, BASENAME_GROUP)
  File "/home/build/libreswan-web/script-repo/testing/utils/fab/shell.py", line 98, in check_prompt_group
    found = match.group(field).decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by cagney** [comment]
the .decode('utf-8') is gone

**Comment by farzad1278** [comment]
> https://testing.libreswan.org/v4.6-144-g303fab99cc-main/xauth-pluto-25-lsw299/OUTPUT/
> ```
> INFO xauth-pluto-25-lsw299 w1.north 1:52:58.01/52.01: stop running script 04-north-up.sh after 0.6 seconds
> INFO xauth-pluto-25-lsw299 w1.east 1:52:58.01/52.01: start running script 05-east-established.sh at 2022-02-03 01:19:19.859905
> INFO xauth-pluto-25-lsw299 w1.east 1:52:58.01/52.01: [05-east-established.sh]# ../../guestbin/wait-for.sh --match '^[^|].* #2: IPsec SA established' -- cat /tmp/pluto.log
> DEBUG xauth-pluto-25-lsw299 w1.east 1:52:58.01/52.01: run '../../guestbin/wait-for.sh --match '^[^|].* #2: IPsec SA established' -- cat /tmp/pluto.log' expecting prompt
> DEBUG xauth-pluto-25-lsw299 w1.east 1:52:58.02/52.02: send <<b"../../guestbin/wait-for.sh --match '^[^|].* #2: IPsec SA established' -- cat /tmp/pluto.log\n">>>
> DEBUG xauth-pluto-25-lsw299 w1.east 1:52:58.02/52.02: read <<b'[   46.869211] alg: No test for echainiv(authenc(hmac(sha1),cbc(aes))) (echainiv(authenc(hmac(sha1-generic),cbc(aes-generic))))\r\n'>>>
> DEBUG xauth-pluto-25-lsw299 w1.east 1:53:27.06/1:21.06: read <<b'timeout waiting 30 seconds for cat /tmp/pluto.log to match ^[^|]'>>>
> DEBUG xauth-pluto-25-lsw299 w1.east 1:53:27.06/1:21.07: read <<b'.* #2: IPsec SA established\n'>>>
> DEBUG xauth-pluto-25-lsw299 w1.east 1:53:27.06/1:21.07: read <<b'outp'>>>
> ...
> DEBUG xauth-pluto-25-lsw299 w1.east 1:53:27.07/1:21.07: read <<b'put: |   35 aa d5 9c  3b 93 '>>>
> DEBUG xauth-pluto-25-lsw299 w1.east 1:53:27.07/1:21.07: read <<b'7e e3  86 c2 a9 93  58 0'>>>
> DEBUG xauth-pluto-25-lsw299 w1.east 1:53:27.07/1:21.07: read <<b'7 2c 31   5...;.~.....X.,1\noutput: |   b0 05 f7 9d  cf 49 1d 88  99 aa 98 93  0f f5 eb 6e   .....I.........n\noutput: |   f5 56 3c 2c  21 73 9e 20  c7 22 81 c2  '>>>
> DEBUG xauth-pluto-25-lsw299 w1.east 1:53:27.07/1:21.07: read <<b'b3 d7 ee 33   .V<,!s. .".....3\noutput: |   04 7a 77 f2  8c 6e 35 23  20 5c 70 57  cd 0b d8 a3   .zw..n5# \\pW....\noutput: |   71 75 11 e6  92 da 98 fb  f0 b8 1f 5b                qu.........[\noutput: | **parse ISAKMP Message:\noutput: | '>>>
> DEBUG xauth-pluto-25-lsw299 w1.east 1:53:27.07/1:21.07: match <re.Match object; span=(3344, 3348), match=b'n5# '> contains {'username': None, 'hostname': None, 'basename': None, 'status': None, 'dollar': b'#'}
> INFO xauth-pluto-25-lsw299 w1.east 1:53:27.07/1:21.07: stop running script 05-east-established.sh after 29.6 seconds
> ERROR xauth-pluto-25-lsw299 w1. 1:53:27.07/1:21.07: *** EXCEPTION 'NoneType' object has no attribute 'decode' while running script east:05-east-established.sh ***
> Traceback (most recent call last):
>   File "/home/build/libreswan-web/script-repo/testing/utils/fab/runner.py", line 350, in _process_test
>     test_domain.read_file_run(script.path)
>   File "/home/build/libreswan-web/script-repo/testing/utils/fab/runner.py", line 139, in read_file_run
>     status = self.console.run(line, timeout=TEST_TIMEOUT)
>   File "/home/build/libreswan-web/script-repo/testing/utils/fab/shell.py", line 224, in run
>     status = check_prompt(self.logger, self.child.match,
>   File "/home/build/libreswan-web/script-repo/testing/utils/fab/shell.py", line 113, in check_prompt
>     check_prompt_group(logger, match, basename, BASENAME_GROUP)
>   File "/home/build/libreswan-web/script-repo/testing/utils/fab/shell.py", line 98, in check_prompt_group
>     found = match.group(field).decode('utf-8')
> AttributeError: 'NoneType' object has no attribute 'decode'
> ```
