### ISSUE TITLE
by default, responding using same DIGSIG as request?

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#639]
For instance, android uses PKCS#1 1.5 RSA DIGSIG, and we respond with the (perfectly reasonable RSASSA_PSS, android does this:

```
     Caused by: android.net.ipsec.ike.exceptions.AuthenticationFailedException: Unrecognized ASN.1 objects for Signature algorithm and Hash
        at com.android.internal.net.ipsec.ike.message.IkeAuthDigitalSignPayload.bytesToJavaStandardSignAlgoName(IkeAuthDigitalSignPayload.java:240)
        at com.android.internal.net.ipsec.ike.message.IkeAuthDigitalSignPayload.<init>(IkeAuthDigitalSignPayload.java:152)
        at com.android.internal.net.ipsec.ike.message.IkeAuthPayload.getIkeAuthPayload(IkeAuthPayload.java:86)
        at com.android.internal.net.ipsec.ike.message.IkePayloadFactory$IkePayloadDecoder.decodeIkePayload(IkePayloadFactory.java:76)
        at com.android.internal.net.ipsec.ike.message.IkePayloadFactory.getIkePayload(IkePayloadFactory.java:158)
        at com.android.internal.net.ipsec.ike.message.IkeMessage.decodePayloadList(IkeMessage.java:169)
        at com.android.internal.net.ipsec.ike.message.IkeMessage.access$100(IkeMessage.java:63)
        at com.android.internal.net.ipsec.ike.message.IkeMessage$IkeMessageHelper.decode(IkeMessage.java:701)
        at com.android.internal.net.ipsec.ike.message.IkeMessage$IkeMessageHelper.decode(IkeMessage.java:595)
        at com.android.internal.net.ipsec.ike.message.IkeMessage.decode(IkeMessage.java:141)
        at com.android.internal.net.ipsec.ike.IkeSessionStateMachine$BusyState.handleReceivedIkePacket(IkeSessionStateMachine.java:1882)
        at com.android.internal.net.ipsec.ike.IkeSessionStateMachine$BusyState.processStateMessage(IkeSessionStateMachine.java:1792) 
        at com.android.internal.net.ipsec.ike.IkeSessionStateMachine$CreateIkeLocalIkeAuth.processStateMessage(IkeSessionStateMachine.java:3754) 
        at com.android.internal.net.ipsec.ike.AbstractSessionStateMachine$ExceptionHandlerBase.processMessage(AbstractSessionStateMachine.java:126) 
        at com.android.internal.net.ipsec.ike.utils.StateMachine$SmHandler.processMsg(StateMachine.java:993) 
        at com.android.internal.net.ipsec.ike.utils.StateMachine$SmHandler.handleMessage(StateMachine.java:810) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by cagney** [comment]
See interop-ikev2-strongswan-36-initiator-sha1-sha2-rsa_pss-yes.
