### ISSUE TITLE
ASSERTION FAILED: helper_threads_started == helper_threads_stopped

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#708]
This:
```
FATAL ERROR: ...
```
eventually calls `libreswan_exit()` which tries to exit pluto without first stopping the event loop.  It leads to:
```
ABORT: ASSERTION FAILED: helper_threads_started == helper_threads_stopped (free_server_helper_jobs() +605 programs/pluto/server_pool.c)
[...]
#4  0x00aef966 in free_server_helper_jobs () at /source/programs/pluto/server_pool.c:605
#5  0x00b41330 in exit_epilogue () at /source/programs/pluto/pluto_shutdown.c:144
#6  0x00b414b8 in libreswan_exit (exit_code=exit_code@entry=PLUTO_EXIT_FAIL) at /source/programs/pluto/pluto_shutdown.c:82
#7  0x00b6ddb2 in fatal_errno (rc=rc@entry=PLUTO_EXIT_FAIL, logger=logger@entry=0xbfb4047c, error=47, fmt=fmt@entry=0xbaa6c2 "bind(%s) failed in %s()") at /source/lib/libswan/fatal.c:59
```
because the helper threads are still running (during an orderly shutdown the helper threads are stopped and then the event loop exits).

**Comment by cagney** [comment]
fixed in mainline
